version: "3.1"
services:
  api:
    build:
      dockerfile: dockerfiles/api.dockerfile
      context: .
    ports:
    - 6606:6606
    depends_on:
      - db
    environment:
      - DATABASE_HOST=p_database
    links:
      - db:p_database

  refresher:
    build:
      dockerfile: ./dockerfiles/refresher.dockerfile
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_HOST=p_database
    links:
      - db:p_database
    restart: always

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=productator
      - MYSQL_DATABASE=productator
    volumes:
      - ./mysql_dumps:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
